### ISSUE TITLE
Bug: Configuration Upgrade Fails Due to Missing config_version Field

### ISSUE THREAD

**Issue by sergiotejon** [freepik-company/fc-py-cogito#102]
**Description:**

When running the `cogito-cli config upgrade` command, the configuration file is not upgraded to a new version if it does not contain the `config_version` field. The command incorrectly assumes that the current version of the file is the latest, resulting in no upgrade being performed. 

**Steps to Reproduce:**
1. Use a configuration file without the `config_version` field:
   ```yaml
   cogito:
     server:
       readiness_file: /tmp/cogito-readiness.lock
       cache_dir: /tmp/cogito
       description: Inference server
       threads: 4
       fastapi:
         access_log: true
         debug: false
         host: 127.0.0.1
         port: 8000
       name: Cogito ergo sum
       route:
         description: Make a single prediction
         name: Predict
         path: /v1/predict
         predictor: predict:Predictor
         tags:
           - predict
       version: 0.1.0
     training: { }
   ```
2. Run the command `cogito-cli config upgrade`.

**Expected Behavior:**
The configuration file should be upgraded to include the latest version information.

**Actual Behavior:**
The command outputs `Configuration is already at the latest version`, and the configuration file is not upgraded.

**Proposed Solution:**
Treat a configuration file without a `config_version` field as if it had the `config_version` field set to 0, instead of assuming it is at the latest version.

**Environment:**
- Cogito Version: 0.3.0a0
- Python Version: 3.13.1

**Comment by sergiotejon** [comment]
If you set `config_version: 0` at the root of the configuration file and run the upgrade again, it works as expected.

```yaml
config_version: 0
cogito:
  server:
    readiness_file: /tmp/cogito-readiness.lock
    cache_dir: /tmp/cogito
    description: Inference server
    threads: 4
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      predictor: predict:Predictor
      tags:
        - predict
    version: 0.1.0
  training: { }
```
