### ISSUE TITLE
Feature Request: Add New Components (Plugins) to Cogito Core

### ISSUE THREAD

**Issue by sergiotejon** [freepik-company/fc-py-cogito#108]
#### Description
We propose adding new components (plugins) to the Cogito core to enhance its functionality. This feature will allow users to extend Cogito with specific components tailored to their needs, such as deployment and user interface capabilities.

#### Purpose and Benefits
- **Extensibility**: Users can add custom components to fit their specific use cases.
- **Modularity**: Separation of concerns by isolating different functionalities into distinct components.
- **Scalability**: Easier to maintain and scale the application by adding new features as plugins.

#### Examples of Components
- **Deploy Component**: Manages the deployment of machine learning models.
- **User Interface Component**: Provides a user interface for interacting with the Cogito core.

#### Structure of cogito.yaml
To implement these components, we will add new structures in the root path of the `cogito.yaml` configuration file. Each component will have its own configuration section.

#### Example: Deploy Component
```yaml
cogito:
  predictor: predict:Predictor
  server:
    cache_dir: /tmp/cogito
    description: Inference server
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    readiness_file: /tmp/cogito-readiness.lock
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      tags:
      - predict
    threads: 4
    version: 0.1.0
  trainer: 'train:Trainer'
  deploy:
    manager: deploy:DeployManager
    method: online
    target: /deployments
config_version: 1
```

#### Example: User Interface Component
```yaml
cogito:
  predictor: predict:Predictor
  server:
    cache_dir: /tmp/cogito
    description: Inference server
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    readiness_file: /tmp/cogito-readiness.lock
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      tags:
      - predict
    threads: 4
    version: 0.1.0
  trainer: 'train:Trainer'
ergo:
  user_interface:
    framework: react
    theme: dark
    entryPoint: /ui
  disponendum_est:
    XXXX: xxxx
    YYYY: yyyy
config_version: 1
```

### Review and Submission
Please review the above description and examples to ensure they meet the requirements for the new feature. Once reviewed, submit the issue on the GitHub repository to request the addition of these new components to the Cogito core.
