### ISSUE TITLE
Remove inferia.yaml args and response

### ISSUE THREAD

**Issue by alepalma91** [freepik-company/fc-py-cogito#57]
**Title:** Remove API request and response specifications from `inferia.yaml`

**Description:**
The current `inferia.yaml` file contains specifications for API requests and responses, which can be confusing for new developers. These details are actually defined in the `predict.py` file. To avoid confusion, we should remove the API request and response specifications from `inferia.yaml`.

**Changes Needed:**
- Remove the following section from `inferia.yaml`:
  ```
  route:
    args:
    - description: The prompt to generate text from
      name: prompt
      type: str
    description: Make a single prediction
    name: Predict
    path: /v1/predict
    predictor: predict:Predictor
    response:
      description: The generated text
      type: PredictResponse
    tags:
    - predict
    threads: 1
  ```

**Clarification:**
The interfaces for API requests and responses are defined in `predict.py` under the `Predictor` class and `PredictResponse` model.

**References:**
- [inferia.yaml](https://github.com/freepik-company/fc-py-inferia/blob/main/examples/inferia.yaml)
- [predict.py](https://github.com/freepik-company/fc-py-inferia/blob/main/examples/predict.py)
