### ISSUE TITLE
Add Training Configuration to inferia.yaml with Autogeneration Scaffold

### ISSUE THREAD

**Issue by sergiotejon** [freepik-company/fc-py-cogito#62]
#### Description
We need to add a new training configuration section to the `inferia.yaml` file to enable running training sessions for a new AI model using the inferia CLI. This section should be similar to the prediction configuration but focused on training. Additionally, we need to include a scaffold to autogenerate the training class, similar to how it's done with the prediction.

#### Proposed Configuration
Here is the proposed `training` section to be added to the `inferia.yaml` file:

```yaml
inferia:
  server:
    cache_dir: /tmp/inferia
    description: Inference server
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Sapientia per Inferentiam
    route:
      args:
      - description: The prompt to generate text from
        name: prompt
        type: str
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      predictor: predict:Predictor
      response:
        description: The generated text
        type: PredictResponse
      tags:
      - predict
      threads: 1
    version: 0.1.0
  training:
    description: Training configuration
    args:
    - description: The dataset to use for training
      name: dataset
      type: str
    - description: The number of epochs to train
      name: epochs
      type: int
    - description: The learning rate for the optimizer
      name: learning_rate
      type: float
    name: Train
    path: /v1/train
    trainer: train:Trainer
    response:
      description: Training results
      type: TrainResponse
    tags:
    - train
    threads: 2
```

#### Autogeneration Scaffold
To autogenerate the training class, we can follow a similar approach to the prediction class generation. Here's an example scaffold for the training class:

```python
# train.py
from inferia.base import BaseTrainer

class Trainer(BaseTrainer):
    def __init__(self, dataset: str, epochs: int, learning_rate: float):
        self.dataset = dataset
        self.epochs = epochs
        self.learning_rate = learning_rate

    def train(self):
        # Implement the training logic here
        pass

class TrainResponse:
    def __init__(self, message: str):
        self.message = message
```

#### Steps to Implement
1. Add the above `training` section to the `inferia.yaml` file.
2. Implement the `Trainer` class and `TrainResponse` class as shown in the scaffold.
3. Update the inferia CLI to support the new `/v1/train` endpoint.

#### Additional Notes
- This feature aims to enhance the AI model's capabilities by providing a structured way to train the model using the inferia CLI.
- Ensure proper validation and error handling for the new training configuration.
