### ISSUE TITLE
Update config.yaml to reflect project evolution (API RESTful + API SDK + CLI)

### ISSUE THREAD

**Issue by sergiotejon** [freepik-company/fc-py-cogito#93]
The config file could be tidied up to reflect the project evolution (interfaces API RESTful + API SDK + CLI).

Current config file:
```yaml
  server:
    readiness_file: /tmp/cogito-readiness.lock
    cache_dir: /tmp/cogito
    description: Inference server
    threads: 4
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      predictor: predict:Predictor
      tags:
        - predict
    version: 0.1.0
```

Example of final config file:

```yaml
config_version: 1 # Version of the cogito.yaml file.

cogito:

  core:
    predictor: predict:Predictor
    trainer: train:Trainer

  server:
    readiness_file: /tmp/cogito-readiness.lock
    cache_dir: /tmp/cogito
    description: Inference server
    threads: 4
    fastapi:
      access_log: true
      debug: false
      host: 127.0.0.1
      port: 8000
    name: Cogito ergo sum
    route:
      description: Make a single prediction
      name: Predict
      path: /v1/predict
      tags:
        - predict
    version: 0.1.0
```

The field `config_version` could be used to maintain different versions of the config file for retro compatibility.

The main goal is to set the predictor and trainer classes in a global configuration space.
